name: Playback Issue
description: Report a problem with the playback of video or audio
labels: [Bug, Needs Triage]
body:
  - type: input
    id: version
    attributes:
      label: What version of Video.js are you using?
      description: Please include all relevant versions. If not using the latest version, explain why not in the description below.
      placeholder: e.g. vX.Y.Z
    validations:
      required: true
  - type: input
    id: plugins
    attributes:
      label: Video.js plugins used
  - type: input
    id: browser
    attributes:
      label: What browser (including version) are you using?
      placeholder: e.g. Chrome 99.0.4844.51 (Official Build) (x86_64)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What OS and version are you using?
      placeholder: e.g. Windows 10
    validations:
      required: true
  - type: input
    id: testcase
    attributes:
      label: URL of stream, or link to test case
      description: Please provide a test stream or page.
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give an overview of the issue.
    validations:
      required: true
  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue.
    validations:
      required: true
      value: |
        1.
        2.
        3.
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
    validations:
      required: true

